# Generated by Django 5.1.3 on 2024-12-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_situacao_options_remove_user_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="user",
        ),
    ]
