# Generated by Django 5.0.6 on 2024-07-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_adotante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adotante",
            name="cpf",
            field=models.IntegerField(max_length=9),
        ),
    ]
