# Generated by Django 5.1.3 on 2024-12-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_animal_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="status",
        ),
    ]
