# Generated by Django 5.0.6 on 2024-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_adotante_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adotante",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="adotante",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="adotante",
            name="telefone",
            field=models.CharField(max_length=13),
        ),
    ]
