# Generated by Django 5.1.3 on 2024-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.IntegerField(
                blank=True, help_text="Contact", max_length=15, null=True, verbose_name="contact"
            ),
        ),
    ]
