# Generated by Django 5.0.6 on 2024-08-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_voluntario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Situacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=30)),
                ("descricao", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Adotante",
        ),
        migrations.DeleteModel(
            name="Voluntario",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
