# Generated by Django 5.1.3 on 2024-12-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_user_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, help_text="Name", max_length=255, null=True, verbose_name="name"),
        ),
    ]
