# Generated by Django 5.1 on 2024-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_especie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Raca",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Raca", models.CharField(max_length=100)),
            ],
        ),
    ]
