# Generated by Django 5.1.3 on 2024-12-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
