# Generated by Django 5.1.3 on 2024-12-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_animal_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="situacao",
            name="descricao",
        ),
    ]
