# Generated by Django 5.1.1 on 2024-10-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_user_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adocao",
            options={"verbose_name": "Adoção", "verbose_name_plural": "Adoções"},
        ),
        migrations.AlterModelOptions(
            name="animal",
            options={"ordering": ["nome"], "verbose_name": "Animal", "verbose_name_plural": "Animais"},
        ),
        migrations.AlterModelOptions(
            name="raca",
            options={"verbose_name": "Raça", "verbose_name_plural": "Raças"},
        ),
        migrations.RemoveField(
            model_name="raca",
            name="raca",
        ),
        migrations.AlterField(
            model_name="adocao",
            name="observacoes",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="idade",
            field=models.PositiveIntegerField(),
        ),
    ]
