# Generated by Django 5.1.1 on 2024-10-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_adocao_options_alter_animal_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raca",
            name="raca",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
